### ISSUE TITLE
Combine Bag

### ISSUE THREAD

**Issue by crazedmeph** [kyokokken/jGoose#1]
This code appears to have an issue when opening the combine bag. The only thing you see is a blank screen for the combine bag. Anyway you can help on fixing this?

**Comment by crazedmeph** [comment]
Looks like the issues is in Window.create for case CombineBag. Change the WindowFrames.TenSlot to WindowFrames.__dummy_enum_18. Once I get my code in git I will create a pull request if it is not fixed before that. Dunno if this repo is still active or not.

**Comment by kyokokken** [comment]
Yeah this project has been inactive for a while.
About the combine bag bug, I've since lost the Aspereta client so I can't even test it.
Thanks for the pull request.

**Comment by crazedmeph** [comment]
Hey Kyokokken, would you like the client again? I have done so many changes to this project but it is not in git..... And there are still some bugs. I fixed Aggro bugs and a few others. I also made saving threaded and I made it a stand alone client that you can execute commands from. But, at the moment everything works great except two bugs I have found so far. (Which are rare) 1) Concurrent List modification (Which I just havent gotten around to fixing). And 2) Mysql bug where it times out after a full day of no one on the server. (Which is not a bug with my code). The 1st is a bug with my threads that I need to fix. Do you happen to know of a command that I can rebase my current code that is not in git on this repo? 

![application](https://cloud.githubusercontent.com/assets/4148270/18373219/5104d886-7610-11e6-964d-387115e46314.PNG)

**Comment by crazedmeph** [comment]
Also, do you happen to have a skype or discord that we can actually talk on instead of comments? So we can collaborate on getting this in to git?
